name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: localhost
      DATABASE_PORT: 3306
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: timezone_api

    steps:
      - uses: actions/checkout@v2

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: ${{ env.DATABASE_NAME }}
          mysql user: ${{ env.DATABASE_USER }}
          mysql password: ${{ env.DATABASE_PASSWORD }}

      - name: install
        run: npm ci

      - name: test
        run: |
          npm test
          npm run test:e2e
